{% set name = "BFEE2" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba3d2bde0b34f6253a4328a9926a8db916c8b850966aac671c106aa0fa04cf39

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:

  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - appdirs
    - MDAnalysis
    - matplotlib-base
    - numpy
    - Pyside2

test:
  imports:
    - BFEE2

about:
  home: https://github.com/fhh2626/BFEE2
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Binding Free Energy Estimator 2
  description: |
    Binding free energy estimator (BFEE) is a python-based 
    software that automates absolute binding free energy
    calculations through either the alchemical or geometric
    route by molecular dynamics simulations.
  doc_url: https://github.com/fhh2626/BFEE2
  dev_url: https://github.com/fhh2626/BFEE2/tree/dev

extra:
  recipe-maintainers:
    - HanatoK
    - fhh2626
